name: ci-node-workflow
on: [push]
jobs:
  check-application:
    runs-on: ubuntu:18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
    # - run: npm ci
    - run: npm test    
